### 1. NORMALIZATION PROBLEM

In [1]:
import numpy as np 

In [3]:
x = np.random.random((5,5))

In [5]:
print (x)

[[0.27312415 0.05040423 0.20381785 0.55202663 0.8623323 ]
 [0.15528426 0.77577545 0.05780132 0.94814713 0.9662843 ]
 [0.5698994  0.8680953  0.16028946 0.35520336 0.77394194]
 [0.44753221 0.85487368 0.26892239 0.62350982 0.47903191]
 [0.13163845 0.10369777 0.10012453 0.23785478 0.3036725 ]]


In [7]:
a = x.mean()

In [9]:
b = x.std()

In [11]:
normal = (x-a)/b

In [13]:
print (normal)

[[-0.56426812 -1.29574922 -0.79189145  0.35173383  1.37087358]
 [-0.95129077  1.08659412 -1.27145489  1.65271603  1.71228407]
 [ 0.41043354  1.38980106 -0.93485213 -0.29469463  1.0805723 ]
 [ 0.00854186  1.34637715 -0.57806802  0.58650673  0.11199659]
 [-1.02895091 -1.12071676 -1.13245238 -0.68010365 -0.46393792]]


In [15]:
np.save ('X_normalized.npy', normal)

## 2. Divisible by 3 Problem

In [21]:
a = np.arange(1,101)
e = np.square (a)
m = e.reshape (10,10)

print(m)

[[    1     4     9    16    25    36    49    64    81   100]
 [  121   144   169   196   225   256   289   324   361   400]
 [  441   484   529   576   625   676   729   784   841   900]
 [  961  1024  1089  1156  1225  1296  1369  1444  1521  1600]
 [ 1681  1764  1849  1936  2025  2116  2209  2304  2401  2500]
 [ 2601  2704  2809  2916  3025  3136  3249  3364  3481  3600]
 [ 3721  3844  3969  4096  4225  4356  4489  4624  4761  4900]
 [ 5041  5184  5329  5476  5625  5776  5929  6084  6241  6400]
 [ 6561  6724  6889  7056  7225  7396  7569  7744  7921  8100]
 [ 8281  8464  8649  8836  9025  9216  9409  9604  9801 10000]]


In [23]:
c = m [m%5==0]
z = c.reshape(4,5)
print (z)

[[   25   100   225   400   625]
 [  900  1225  1600  2025  2500]
 [ 3025  3600  4225  4900  5625]
 [ 6400  7225  8100  9025 10000]]


In [25]:
np.save ('div_by_3.npy',c)